import { ConnectedMailboxProvider } from './connected-mailbox';

export type OAuthTransactionStatus = 'PENDING' | 'CONSUMED' | 'EXPIRED' | 'FAILED';

/** M29 Phase 2 — which real capability an OAuth attempt is requesting, stored on the transaction
 * itself (never inferred) so `MailboxConnectionService`/`InboxConsentService` never conflate "the
 * user re-authorized sending" with "the user granted inbox reading" — two different real consent
 * events, even though Google's incremental-authorization model means they can end up sharing one
 * token. */
export type OAuthCapabilityPurpose = 'SEND_APPLICATION_EMAIL' | 'READ_APPLICATION_REPLIES';

/** A short-lived, single-use, server-side record of one in-flight OAuth authorization attempt —
 * the real CSRF/replay defense (M28.6 Phase 5). See the Prisma model's own doc comment for why
 * the callback derives the acting user from `userId` here, never from a bearer token on the
 * callback request itself. */
export interface OAuthTransactionRecord {
  readonly id: string;
  readonly state: string;
  readonly userId: string;
  readonly provider: ConnectedMailboxProvider;
  readonly capability: OAuthCapabilityPurpose;
  readonly codeVerifier: string;
  readonly redirectUri: string;
  readonly status: OAuthTransactionStatus;
  readonly expiresAt: Date;
  readonly consumedAt: Date | null;
  readonly createdAt: Date;
}

export interface CreateOAuthTransactionInput {
  /** Generated by the application-layer `OAuthSecurityService` via `crypto.randomBytes` — the
   * repository never generates its own security-critical randomness (a pure persistence
   * concern/security concern split, matching this codebase's established layering). */
  readonly state: string;
  readonly userId: string;
  readonly provider: ConnectedMailboxProvider;
  readonly capability: OAuthCapabilityPurpose;
  readonly codeVerifier: string;
  readonly redirectUri: string;
  readonly expiresAt: Date;
}
