export type {
  InboxMessageDto,
  InboxMessageDetailDto,
  InboxMessageCorrectionDto,
  ApplicationTransitionProposalDto,
  ReplyDraftDto,
  ReplyDraftPlaceholderDto,
  ExtractedRecruitmentFactsDto,
  DateExtractionDto,
  NextActionRecommendationDto,
  NotificationDto,
  NotificationPreferenceDto,
  StartInboxConsentResponseDto,
  CorrectClassificationRequestDto,
  CorrectFactsRequestDto,
  ConfirmApplicationMatchRequestDto,
  CreateReplyDraftRequestDto,
  EditReplyDraftRequestDto,
  ApproveAndSendDraftRequestDto,
} from '@german-job-engine/shared-types';
export type {
  InboxCapabilityStatus,
  CorrelationStatus,
  ReplyPrimaryCategory,
  ReplySecondaryLabel,
  ClassificationSource,
  InboxMessageReviewStatus,
  ProposedApplicationAction,
  ApplicationTransitionProposalStatus,
  ReplyDraftType,
  ReplyDraftStatus,
  NotificationKind,
} from '@german-job-engine/shared-types';
