import { CampaignTargetStatus } from '@german-job-engine/shared-types';
import { StatTile } from '@/components/ui/stat-tile';
import type { CampaignDto, CampaignExecutionStatusDto } from '../types';

function countFor(breakdown: CampaignExecutionStatusDto['targetBreakdown'], status: CampaignTargetStatus): number {
  return breakdown.find((entry) => entry.status === status)?.count ?? 0;
}

/**
 * docs/campaign-workspace/. Section 7, Operational Analytics. The milestone's own example list
 * (emails sent, deliveries confirmed, replies, interviews, average processing time) requires
 * cross-referencing individual Applications generated by this campaign — no such query exists:
 * Application has no real `campaignId` field and no endpoint accepts a campaign filter
 * (docs/campaign-workspace/03-integration-points.md). Every tile below is instead computed
 * directly from real, live campaign data (`CampaignExecutionStatusDto.targetBreakdown`/
 * `goalProgress`, `CampaignDto.targetsCount`/`batchesCount`) — including two real ratios
 * (`Coverage`, `Failure rate`) computed from two real counts, not estimated.
 */
export function OperationalAnalytics({
  campaign,
  executionStatus,
}: {
  campaign: CampaignDto;
  executionStatus: CampaignExecutionStatusDto;
}) {
  const dispatched = executionStatus.goalProgress.dispatched;
  const target = executionStatus.goalProgress.target;
  const coverage = target > 0 ? Math.round((dispatched / target) * 100) : 0;
  const failed = countFor(executionStatus.targetBreakdown, CampaignTargetStatus.FAILED);
  const failureRate = campaign.targetsCount > 0 ? Math.round((failed / campaign.targetsCount) * 100) : 0;

  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
      <StatTile label="Total targets" value={String(campaign.targetsCount)} />
      <StatTile label="Batches" value={String(campaign.batchesCount)} />
      <StatTile label="Dispatched" value={`${dispatched} / ${target}`} />
      <StatTile label="Coverage" value={`${coverage}%`} />
      <StatTile label="Failed" value={String(failed)} />
      <StatTile label="Failure rate" value={`${failureRate}%`} />
    </div>
  );
}
