export enum CampaignStrategyType {
  CONSERVATIVE = 'CONSERVATIVE',
  BALANCED = 'BALANCED',
  AGGRESSIVE = 'AGGRESSIVE',
  OUTCOME_OPTIMIZED = 'OUTCOME_OPTIMIZED',
  AI_OPTIMIZED = 'AI_OPTIMIZED',
  CUSTOM = 'CUSTOM',
}
