export enum CampaignReasonCode {
  CANDIDATE_REQUEST = 'CANDIDATE_REQUEST',
  GOAL_REACHED = 'GOAL_REACHED',
  RISK_THRESHOLD_EXCEEDED = 'RISK_THRESHOLD_EXCEEDED',
  COMPANY_FATIGUE_DETECTED = 'COMPANY_FATIGUE_DETECTED',
  DUPLICATE_DETECTED = 'DUPLICATE_DETECTED',
  RATE_LIMIT_REACHED = 'RATE_LIMIT_REACHED',
  EXECUTION_WINDOW_CLOSED = 'EXECUTION_WINDOW_CLOSED',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
  SYSTEM_SIGNAL = 'SYSTEM_SIGNAL',
  POLICY_TIMEOUT = 'POLICY_TIMEOUT',
  OTHER = 'OTHER',
}
