export enum CompanyIndustry {
  IT_SOFTWARE = 'IT_SOFTWARE',
  ENGINEERING = 'ENGINEERING',
  MANUFACTURING = 'MANUFACTURING',
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  RETAIL = 'RETAIL',
  LOGISTICS = 'LOGISTICS',
  CONSTRUCTION = 'CONSTRUCTION',
  HOSPITALITY = 'HOSPITALITY',
  EDUCATION = 'EDUCATION',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER',
}
