export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  INTERNSHIP = 'INTERNSHIP',
  WORKING_STUDENT = 'WORKING_STUDENT',
  FREELANCE = 'FREELANCE',
  AUSBILDUNG = 'AUSBILDUNG',
  DUAL_STUDY = 'DUAL_STUDY',
}
