export enum TransitionReasonCode {
  CANDIDATE_REQUEST = 'CANDIDATE_REQUEST',
  COMPANY_DECISION = 'COMPANY_DECISION',
  POSITION_FILLED = 'POSITION_FILLED',
  QUALIFICATION_MISMATCH = 'QUALIFICATION_MISMATCH',
  POLICY_TIMEOUT = 'POLICY_TIMEOUT',
  DATA_RETENTION = 'DATA_RETENTION',
  DUPLICATE = 'DUPLICATE',
  SYSTEM_SIGNAL = 'SYSTEM_SIGNAL',
  OTHER = 'OTHER',
}
